services:
  accounts:
    image: "sparshverma/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sv
  cards:
    image: "sparshverma/cards:v1"
    container_name: cards-ms
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sv
  loans:
    image: "sparshverma/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sv
networks:
  sv:
    driver: "bridge"
