services:
  network-deploy-service:
    networks:
      - sv
  microservice-base-config:
    extends:
      service: network-deploy-service
#    deploy:
#      resources:
#        limits:
#          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-base-config1:
    extends:
      service: network-deploy-service
#    deploy:
#      resources:
#        limits:
#          memory: 2048m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: native

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"